# --- CONFIGURACIÓN PARA POSTGRESQL (RENDER) ---

# Despliegue
# Nota: Se añade el puerto 5432 y el parámetro sslmode=require necesario para Render
spring.datasource.url=jdbc:postgresql://dpg-d5rkqtffte5s73ccbqbg-a.frankfurt-postgres.render.com:5432/smartchef?sslmode=require
spring.datasource.username=smartchef_user
spring.datasource.password=aqRwV3TkvJdWzoSLhvQXoorhzBmWazDb

# Conexión Local
#spring.datasource.url=jdbc:postgresql://localhost:5432/smartchef
#spring.datasource.username=postgres
#spring.datasource.password=123456

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# IMPORTANTE: Cambiamos el dialecto de MariaDB a PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server.port=8080

# Ruta absoluta para Casa y Clase
usuario.uploads.path=uploads/
